-- =========================================================
-- VIEW: v_monthly_revenue
-- PURPOSE:
-- Analyze total business revenue over time
-- Used for:
-- - Revenue trend charts
-- - Monthly performance tracking
-- =========================================================

CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.v_monthly_revenue AS

SELECT
    -- Year extracted from purchase date
    dd.year,

    -- Month extracted from purchase date
    dd.month,

    -- Total revenue generated per month
    SUM(fo.total_price) AS total_revenue

FROM ECOMMERCE_DB.ANALYTICS.FACT_ORDER_ITEMS fo

-- Join with date dimension for time analysis
JOIN ECOMMERCE_DB.ANALYTICS.DIM_DATE dd
    ON CAST(fo.purchase_ts AS DATE) = dd.full_date

GROUP BY dd.year, dd.month;



-- =========================================================
-- VIEW: v_top_customers
-- PURPOSE:
-- Identify highest spending customers
-- Used for:
-- - Customer segmentation
-- - VIP customer analysis
-- =========================================================

CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.v_top_customers AS

SELECT
    -- Customer unique identifier
    c.customer_id,

    -- Customer state/location
    c.customer_state,

    -- Total spending by customer
    SUM(fo.total_price) AS total_revenue

FROM ECOMMERCE_DB.ANALYTICS.FACT_ORDER_ITEMS fo

-- Join customer dimension
JOIN ECOMMERCE_DB.ANALYTICS.DIM_CUSTOMERS c
    ON fo.customer_id = c.customer_id

GROUP BY
    c.customer_id,
    c.customer_state;



-- =========================================================
-- VIEW: v_product_performance
-- PURPOSE:
-- Analyze product category performance
-- Used for:
-- - Best selling categories
-- - Product revenue analysis
-- =========================================================

CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.v_product_performance AS

SELECT
    -- Product category name
    p.product_category_name,

    -- Revenue generated by category
    SUM(f.total_price) AS total_revenue,

    -- Number of unique orders
    COUNT(DISTINCT f.order_id) AS total_orders

FROM ECOMMERCE_DB.ANALYTICS.FACT_ORDER_ITEMS f

-- Join product dimension
JOIN ECOMMERCE_DB.ANALYTICS.DIM_PRODUCTS p
    ON f.product_id = p.product_id

GROUP BY p.product_category_name;



-- =========================================================
-- VIEW: v_delivery_performance
-- PURPOSE:
-- Analyze delivery efficiency
-- Used for:
-- - Logistics monitoring
-- - Shipping performance analysis
-- =========================================================

CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.v_delivery_performance AS

SELECT
    -- Average delivery time
    AVG(delivery_days) AS avg_delivery_days,

    -- Longest delivery duration
    MAX(delivery_days) AS max_delivery_days,

    -- Fastest delivery duration
    MIN(delivery_days) AS min_delivery_days

FROM ECOMMERCE_DB.ANALYTICS.FACT_ORDER_ITEMS;



-- =========================================================
-- VIEW: v_payment_analysis
-- PURPOSE:
-- Analyze customer payment behavior
-- Used for:
-- - Payment method distribution
-- - Payment value analysis
-- =========================================================

CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.v_payment_analysis AS

SELECT
    -- Payment method used
    payment_type,

    -- Total number of transactions
    COUNT(*) AS total_transactions,

    -- Total payment amount
    SUM(payment_value) AS total_payment_value

FROM ECOMMERCE_DB.STAGING.ORDER_PAYMENTS

GROUP BY payment_type;
--===============================================================
--===============================================================
CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.v_aov AS
SELECT
    COUNT(DISTINCT order_id) AS total_orders,
    SUM(total_revenue) AS total_revenue,
    SUM(total_revenue) / COUNT(DISTINCT order_id) AS avg_order_value
FROM ECOMMERCE_DB.ANALYTICS.FACT_ORDER_ITEMS;
--===============================================================
--===============================================================
CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.v_cancellation_analysis AS
SELECT
    COUNT(DISTINCT order_id) AS canceled_orders,
    SUM(total_revenue) AS lost_revenue
FROM ECOMMERCE_DB.ANALYTICS.FACT_ORDER_ITEMS
WHERE order_status = 'canceled';
--===============================================================
--===============================================================
CREATE OR REPLACE VIEW ECOMMERCE_DB.ANALYTICS.v_sales_by_state AS
SELECT
    c.customer_state,
    SUM(f.total_revenue) AS total_revenue,
    COUNT(DISTINCT f.order_id) AS total_orders
FROM ECOMMERCE_DB.ANALYTICS.FACT_ORDER_ITEMS f
JOIN ECOMMERCE_DB.ANALYTICS.DIM_CUSTOMERS c
    ON f.customer_id = c.customer_id
GROUP BY c.customer_state;